name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.5.0
        with:
          submodules: "true"

      - name: Get dependencies
        run: |
          go mod download

      - name: Test
        env:
          MNEMONICS: ${{ secrets.MNEMONICS }}
          NETWORK: dev
        run: go test -v `go list ./... | grep -v integration_tests`
